version: "2"
services:
  mu.slackbot:
    build: .
    tty: true
    container_name: slack-bot
    environment:
      - DEFAULT_SLACK_CHANNEL
      - SLACK_BOT_TOKEN
      - SLACK_APP_TOKEN
    # lintは一旦ごめんなさい．．．（なんちゃってtypingでエラーばかりでるので．）
    command: >
      /bin/bash -c 'pysen run format 
      && python src/main.py'
    working_dir: /app/src
    volumes:
      - $PWD:/app/src
