[tool.pysen]
version = "0.9"

[tool.pysen.lint]
# pysen run format
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = false
mypy_preset = "strict"
line_length = 80
py_version = "py38"
[[tool.pysen.lint.mypy_targets]]
  paths = ["src/"]

# typingが訳わからん